# Generated by Django 5.2.5 on 2025-08-18 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("block_user", "Может блокировать пользователей"),
                    ("disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")],
                default="user",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение аватара",
                null=True,
                upload_to="users/avatars",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["jfif", "jpg", "jpeg", "png"])
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
